import Header from '@/components/Header'
import './index.css'
import '@/google-fonts/icons.css'
import { Nunito_Sans, Roboto, Nunito } from 'next/font/google';

const nunito = Nunito({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Countries App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={nunito.className}>
      <body className='bg-slate-200 dark:bg-slate-800'>
        <Header />

        <div className='w-[90%] mx-auto'>
          {children}
        </div>
        
      </body>
    </html>
  )
}
